# Generates and uploads an image of Robotics-Database using the desired tag and branches
name: Generate tagged Robotics Database image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker Image Tag'
        required: true
        default: test
      latest:
        description: 'Upload as latest'
        type: boolean
        required: true
        default: false
      Name:
        description: 'Name of postgres database'
        required: true
        default: academy_db
      UserName:
        description: 'User name for postgres database'
        required: true
        default: user-dev
      PASSWORD:
        description: 'Password for postgres database'
        required: true
        default: robotics-academy-dev

jobs:
  push_to_registry:
    name: Run Test and Update Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo # checking our the code at current commit that triggers the workflow
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch-webserver-id }}
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Pull base image
      #   run: |
      #     sudo apt-get update
      #     cd scripts
      - name: Build and push RADI
        run: |
          cd scripts
          docker build --no-cache -f Dockerfile.database_RA \
            --build-arg IMAGE_TAG=${{ github.event.inputs.tag }} \
            --build-arg POSTGRES_DB=${{ github.event.inputs.Name }} \
            --build-arg POSTGRES_USER=${{ github.event.inputs.UserName }} \
            --build-arg POSTGRES_PASSWORD=${{ github.event.inputs.PASSWORD }} \
            -t jderobot/robotics-database:${{ github.event.inputs.tag }} .
      - name: Upload as Latest
        if:  ${{ inputs.latest }} 
        run: |
            docker image tag jderobot/robotics-database:${{ github.event.inputs.tag }} jderobot/robotics-database:latest
            docker push jderobot/robotics-database:latest
