# Generates and uploads an image of Robotics Academy database using the desired tag and branches
name: Generate tagged Robotics Academy Database image

on:
  workflow_call:
    inputs:
      tag:
        description: 'Docker Image Tag'
        required: true
        default: test
        type: string
      latest:
        description: 'Upload as latest'
        required: true
        default: false
        type: boolean
      RA:
        description: 'Branch of RoboticsAcademy'
        required: true
        default: humble-devel
        type: string
      RI:
        description: 'Branch of Robotics Infrastructure for Universes Database'
        required: true
        default: database
        type: string
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker Image Tag'
        required: true
        default: test
      latest:
        description: 'Upload as latest'
        type: boolean
        required: true
        default: false
      RA:
        description: 'Branch of RoboticsAcademy'
        required: true
        default: humble-devel
      RI:
        description: 'Branch of Robotics Infrastructure for Universes Database'
        required: true
        default: database

jobs:
  push_to_registry:
    name: Run Test and Update Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo # checking our the code at current commit that triggers the workflow
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch-webserver-id }}
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push RA database
        run: |
          cd scripts
          docker build --no-cache -f Dockerfile.database_RA \
            --build-arg IMAGE_TAG=${{ github.event.inputs.tag }} \
            --build-arg ROBOTICS_ACADEMY=${{ github.event.inputs.RA }}\
            --build-arg ROBOTICS_INFRASTRUCTURE=${{ github.event.inputs.RI }} \
            -t jderobot/robotics-database:${{ github.event.inputs.tag }} .
          docker push jderobot/robotics-database:${{ github.event.inputs.tag }}
      - name: Upload as Latest
        if:  ${{ inputs.latest }} 
        run: |
            docker image tag jderobot/robotics-database:${{ github.event.inputs.tag }} jderobot/robotics-database:latest
            docker push jderobot/robotics-database:latest
